server:
  port: 8080

spring:
  datasource:
    name: blog
    url: "jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true"
    username: "root"
    password: "dh991218"
mybatis:
  type-aliases-package: com.ncu.sandy.blog.pojo
  mapperLocations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl